name = "speeddial-sync"
main = "src/index.js"
compatibility_date = "2024-12-01"
account_id = "0fb46808d919893df3ef67c42d8bba36"

[[kv_namespaces]]
binding = "SYNC_KV"
id = "4fc3a16c6f7d4de79e33fcdc43f66960"

[vars]
GOOGLE_CLIENT_ID = "1017927287759-mgaib9am82c58fl9e6u7m7ht10kj1bp9.apps.googleusercontent.com"
ALLOWED_ORIGINS = "chrome-extension://hpmdmgbcjcekhmfalaodhgeemilbepcj,chrome-extension://miphkkgceicjjenpfeajamfdceiapppe"
